### ISSUE TITLE
Add `forEach` key to iterate over values in workflow steps

### ISSUE THREAD

**Issue by yohamta** [dagu-labs/dagu#439]
This feature would allow users to specify a list of values and then execute a command on each of those values.

The `forEach` key would be added to the YAML file to specify the list of values to iterate over, and each value would be passed as a parameter named `$_`, borrowed from Perl's syntax.

For example, the following YAML file would use the `forEach` key to execute a command for each value in the `VALUES` parameter:
```yaml
params:
  VALUES: 20000 20020 20980 212001
steps:
  - name: task1
    forEach: $VALUES
    command: some_task $_
```
